version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
