version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open_pull_requests_limit: 5
    pull_request_branch_name:
      separator: "/"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open_pull_requests_limit: 3
    pull_request_branch_name:
      separator: "/"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open_pull_requests_limit: 3
    pull_request_branch_name:
      separator: "/"
    labels:
      - "dependencies"
