---
title: "Configuration File Standards"
description: "Configuration file best practices TOML YAML Taskfile"
type: "rule"
status: "active"

# Windsurf-specific configuration
windsurf:
  trigger: "glob"
  globs: "pyproject.toml, *.ini, Taskfile.yml, .pre-commit-config.yaml"

# Cursor-specific configuration
cursor:
  alwaysApply: false
  globs: "pyproject.toml, *.ini, Taskfile.yml, .pre-commit-config.yaml"

tags: ["configuration", "toml", "yaml", "taskfile"]

---
related:
  - "/docs/adr/0001-decision.md"

# Configuration File Standards

## TOML Files (pyproject.toml)

**Best practices:**

- Use tables for organization
- Keep dependencies alphabetized
- Version constraints: Use `>=` for lower bound, `<` for upper
- Document non-obvious choices with inline comments

```toml
[project]
name = "mcp-web"
version = "0.1.0"
requires-python = ">=3.10"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
```

## YAML Files

**Common pitfalls:**

- Avoid quotes unless necessary (YAML auto-detects types)
- Use consistent indentation (2 spaces)
- Lists: Use `-` with space
- Multiline strings: Use `|` for preserving newlines

```yaml
# Good
key: value
list:
  - item1
  - item2

# Bad
key: "value"  # Unnecessary quotes
list: [item1, item2]  # Hard to read
```

## Taskfile.yml

**Structure:**

```yaml
version: '3'

tasks:
  test:
    desc: "Run tests"
    cmds:
      - uv run pytest

  lint:
    desc: "Run linting"
    cmds:
      - uv run ruff check .
      - uv run mypy .
```

## Configuration Validation

### TOML Validation

```bash
# Validate TOML syntax
python -c "import tomllib; tomllib.load(open('pyproject.toml', 'rb'))"
```

### YAML Validation

```bash
# Validate YAML syntax
python -c "import yaml; yaml.safe_load(open('config.yaml'))"
```

## Best Practices

### Version Management

- **Pin major versions:** Use `>=1.0,<2.0` for libraries
- **Exact versions:** Use `==1.2.3` for applications
- **Update regularly:** Keep dependencies current

### Security

- **No secrets:** Never commit API keys or passwords
- **Environment variables:** Use `.env` files for secrets
- **Validation:** Validate all configuration inputs

### Documentation

- **Inline comments:** Explain non-obvious choices
- **README updates:** Document new configuration options
- **Examples:** Provide working configuration examples

## Rule Metadata

**File:** `04_config_files.yaml`
**Trigger:** glob (Windsurf) / globs (Cursor)
**Estimated Tokens:** ~800
**Last Updated:** 2025-10-22
**Status:** Active

**Topics Covered:**
- TOML configuration
- YAML configuration
- Taskfile standards
- Configuration validation

**Workflow References:**
- /implement - Configuration updates
- /validate - Configuration validation

**Dependencies:**
- Source: 04_config_files.md
